name: Setup And Deploy 2048 game to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:

  deploy-terraform:
    name: "Deploy Infrastructure"
    runs-on: ubuntu-latest
    timeout-minutes: 45
    defaults:
      run:
        working-directory: './terraform/'
        
    concurrency: 
      group: infra-deployment

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy EKS Infrastructure
        uses: ./.github/actions/deploy-infra
        id: deploy_infra
        env: 
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

      
  deploy:
    runs-on: ubuntu-latest
    needs: deploy-terraform
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Save Terraform Outputs
      id: outputs
      run: |
        echo "::set-output name=vpc_id::$(deploy-terraform output -raw vpc_id)"

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: aws eks update-kubeconfig --name game-cluster --region us-east-1  

    - uses: azure/setup-helm@v4.2.0
      with:
        version: 'latest'
      id: install

    - name: Deploy Game to Kubernetes
      run: kubectl apply -f kube-manifest/

    - name: Deploy Game
      run: |
        helm repo add eks https://aws.github.io/eks-charts
        helm repo update eks
        helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system \
        --set clusterName=game-cluster \
        --set serviceAccount.create=false \
        --set serviceAccount.name=aws-load-balancer-controller \
        --set region=us-east-1 \
        --set vpcId=${{ needs.deploy-terraform.outputs.vpc_id }}
        
    - name: Check Load Balancer
      run: kubectl get ingress -n game-2048
